wandb_version: 1

_wandb:
  desc: null
  value:
    bounding_box/class_labels:
      BoundingBoxDebugger_wandb_delimeter_predictions:
        key: BoundingBoxDebugger_wandb_delimeter_predictions
        type: bounding_box/class_labels
        value:
          '0': prohibitory
          '1': danger
          '2': mandatory
          '3': other
    cli_version: 0.12.14
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.2
    start_time: 1650599121
    t:
      1:
      - 1
      - 3
      - 41
      - 55
      2:
      - 1
      - 3
      - 41
      - 55
      3:
      - 2
      - 16
      4: 3.9.2
      5: 0.12.14
      8:
      - 3
      - 5
artifact_alias:
  desc: null
  value: latest
batch_size:
  desc: null
  value: 16
bbox_interval:
  desc: null
  value: -1
bucket:
  desc: null
  value: ''
cache:
  desc: null
  value: null
cfg:
  desc: null
  value: ''
cos_lr:
  desc: null
  value: false
data:
  desc: null
  value: ../archive/custom.yaml
data_dict:
  desc: null
  value:
    names:
    - prohibitory
    - danger
    - mandatory
    - other
    nc: 4
    path: ../archive
    test: null
    train: C:\Users\alexa\Documents\VT Work\2021-2022 Junior Year\2022 Spring\ECE
      4424 Machine Learning\Project\archive\train\images
    val: C:\Users\alexa\Documents\VT Work\2021-2022 Junior Year\2022 Spring\ECE 4424
      Machine Learning\Project\archive\val\images
device:
  desc: null
  value: ''
entity:
  desc: null
  value: null
epochs:
  desc: null
  value: 100
evolve:
  desc: null
  value: null
exist_ok:
  desc: null
  value: false
freeze:
  desc: null
  value:
  - 0
hyp:
  desc: null
  value:
    anchor_t: 4.0
    box: 0.05
    cls: 0.5
    cls_pw: 1.0
    copy_paste: 0.0
    degrees: 0.0
    fl_gamma: 0.0
    fliplr: 0.5
    flipud: 0.0
    hsv_h: 0.015
    hsv_s: 0.7
    hsv_v: 0.4
    iou_t: 0.2
    lr0: 0.01
    lrf: 0.01
    mixup: 0.0
    momentum: 0.937
    mosaic: 1.0
    obj: 1.0
    obj_pw: 1.0
    perspective: 0.0
    scale: 0.5
    shear: 0.0
    translate: 0.1
    warmup_bias_lr: 0.1
    warmup_epochs: 3.0
    warmup_momentum: 0.8
    weight_decay: 0.0005
image_weights:
  desc: null
  value: false
imgsz:
  desc: null
  value: 640
label_smoothing:
  desc: null
  value: 0.0
local_rank:
  desc: null
  value: -1
multi_scale:
  desc: null
  value: false
name:
  desc: null
  value: exp
noautoanchor:
  desc: null
  value: false
nosave:
  desc: null
  value: false
noval:
  desc: null
  value: false
optimizer:
  desc: null
  value: SGD
patience:
  desc: null
  value: 100
project:
  desc: null
  value: runs\train
quad:
  desc: null
  value: false
rect:
  desc: null
  value: false
resume:
  desc: null
  value: false
save_dir:
  desc: null
  value: runs\train\exp6
save_period:
  desc: null
  value: -1
single_cls:
  desc: null
  value: false
sync_bn:
  desc: null
  value: false
upload_dataset:
  desc: null
  value: false
weights:
  desc: null
  value: yolov5s.pt
workers:
  desc: null
  value: 1
